/** School and major dropdowns shared by the registration form. */

export interface OptionGroup {
  label: string;
  options: string[];
}

/**
 * Every California community college, CSU, UC, and the larger independents,
 * grouped so the nearest schools come first. Anything not listed (out of
 * state, international, high school) can just be typed into the field.
 */
export const SCHOOLS: OptionGroup[] = [
  {
    label: "Orange County community colleges",
    options: [
      "Orange Coast College",
      "Golden West College",
      "Coastline College",
      "Santa Ana College",
      "Santiago Canyon College",
      "Irvine Valley College",
      "Saddleback College",
      "Fullerton College",
      "Cypress College",
    ],
  },
  {
    label: "Southern California community colleges",
    options: [
      "Antelope Valley College",
      "Barstow Community College",
      "Cerritos College",
      "Chaffey College",
      "Citrus College",
      "College of the Canyons",
      "College of the Desert",
      "Compton College",
      "Copper Mountain College",
      "Crafton Hills College",
      "Cuyamaca College",
      "East Los Angeles College",
      "El Camino College",
      "Glendale Community College",
      "Grossmont College",
      "Imperial Valley College",
      "Long Beach City College",
      "Los Angeles City College",
      "Los Angeles Harbor College",
      "Los Angeles Mission College",
      "Los Angeles Pierce College",
      "Los Angeles Southwest College",
      "Los Angeles Trade-Technical College",
      "Los Angeles Valley College",
      "MiraCosta College",
      "Moorpark College",
      "Moreno Valley College",
      "Mt. San Antonio College",
      "Mt. San Jacinto College",
      "Norco College",
      "Oxnard College",
      "Palo Verde College",
      "Palomar College",
      "Pasadena City College",
      "Rio Hondo College",
      "Riverside City College",
      "San Bernardino Valley College",
      "San Diego City College",
      "San Diego Mesa College",
      "San Diego Miramar College",
      "Santa Barbara City College",
      "Santa Monica College",
      "Southwestern College",
      "Ventura College",
      "Victor Valley College",
      "West Los Angeles College",
    ],
  },
  {
    label: "Other California community colleges",
    options: [
      "Allan Hancock College",
      "American River College",
      "Bakersfield College",
      "Berkeley City College",
      "Butte College",
      "Cabrillo College",
      "Cañada College",
      "Cerro Coso Community College",
      "Chabot College",
      "City College of San Francisco",
      "Clovis Community College",
      "College of Alameda",
      "College of Marin",
      "College of San Mateo",
      "College of the Redwoods",
      "College of the Sequoias",
      "College of the Siskiyous",
      "Columbia College",
      "Contra Costa College",
      "Cosumnes River College",
      "Cuesta College",
      "De Anza College",
      "Diablo Valley College",
      "Evergreen Valley College",
      "Feather River College",
      "Folsom Lake College",
      "Foothill College",
      "Fresno City College",
      "Gavilan College",
      "Hartnell College",
      "Lake Tahoe Community College",
      "Laney College",
      "Las Positas College",
      "Lassen Community College",
      "Los Medanos College",
      "Madera Community College",
      "Mendocino College",
      "Merced College",
      "Merritt College",
      "Mission College",
      "Modesto Junior College",
      "Monterey Peninsula College",
      "Napa Valley College",
      "Ohlone College",
      "Porterville College",
      "Reedley College",
      "Sacramento City College",
      "San Joaquin Delta College",
      "San José City College",
      "Santa Rosa Junior College",
      "Shasta College",
      "Sierra College",
      "Skyline College",
      "Solano Community College",
      "Taft College",
      "West Hills College Lemoore",
      "West Valley College",
      "Woodland Community College",
      "Yuba College",
    ],
  },
  {
    label: "California State University",
    options: [
      "Cal Poly Humboldt",
      "Cal Poly Pomona",
      "Cal Poly San Luis Obispo",
      "CSU Bakersfield",
      "CSU Channel Islands",
      "CSU Chico",
      "CSU Dominguez Hills",
      "CSU East Bay",
      "CSU Fullerton",
      "CSU Long Beach",
      "CSU Los Angeles",
      "CSU Maritime Academy",
      "CSU Monterey Bay",
      "CSU Northridge",
      "CSU San Bernardino",
      "CSU San Marcos",
      "CSU Stanislaus",
      "Fresno State",
      "Sacramento State",
      "San Diego State University",
      "San Francisco State University",
      "San José State University",
      "Sonoma State University",
    ],
  },
  {
    label: "University of California",
    options: [
      "UC Berkeley",
      "UC Davis",
      "UC Irvine",
      "UC Los Angeles",
      "UC Merced",
      "UC Riverside",
      "UC San Diego",
      "UC San Francisco",
      "UC Santa Barbara",
      "UC Santa Cruz",
    ],
  },
  {
    label: "Private & independent",
    options: [
      "Azusa Pacific University",
      "Biola University",
      "California Baptist University",
      "California Institute of Technology",
      "California Lutheran University",
      "Chapman University",
      "Claremont McKenna College",
      "Concordia University Irvine",
      "Harvey Mudd College",
      "Loyola Marymount University",
      "Mount Saint Mary's University",
      "National University",
      "Occidental College",
      "Pepperdine University",
      "Pitzer College",
      "Point Loma Nazarene University",
      "Pomona College",
      "Saint Mary's College of California",
      "Santa Clara University",
      "Scripps College",
      "Soka University of America",
      "Stanford University",
      "University of La Verne",
      "University of Redlands",
      "University of San Diego",
      "University of San Francisco",
      "University of Southern California",
      "Vanguard University",
      "Whittier College",
      "Woodbury University",
    ],
  },
];

/** Common majors, grouped. Anything else is typed in free-hand. */
export const MAJORS: OptionGroup[] = [
  {
    label: "Computing & engineering",
    options: [
      "Computer Science",
      "Computer Engineering",
      "Software Engineering",
      "Computer Information Systems",
      "Information Technology",
      "Cybersecurity",
      "Data Science",
      "Game Design & Development",
      "Robotics",
      "Aerospace Engineering",
      "Biomedical Engineering",
      "Chemical Engineering",
      "Civil Engineering",
      "Electrical Engineering",
      "Industrial Engineering",
      "Mechanical Engineering",
    ],
  },
  {
    label: "Math & sciences",
    options: [
      "Mathematics",
      "Statistics",
      "Physics",
      "Chemistry",
      "Biology",
      "Biochemistry",
      "Neuroscience",
      "Environmental Science",
      "Geology",
      "Astronomy",
    ],
  },
  {
    label: "Business & economics",
    options: [
      "Accounting",
      "Business Administration",
      "Economics",
      "Entrepreneurship",
      "Finance",
      "Management Information Systems",
      "Marketing",
      "Supply Chain Management",
    ],
  },
  {
    label: "Arts, design & media",
    options: [
      "Animation",
      "Architecture",
      "Communications",
      "Film & Media Studies",
      "Graphic Design",
      "Industrial Design",
      "Journalism",
      "Music",
      "Studio Art",
      "UX / Interaction Design",
    ],
  },
  {
    label: "Health & social sciences",
    options: [
      "Anthropology",
      "Criminal Justice",
      "Education",
      "Kinesiology",
      "Nursing",
      "Political Science",
      "Psychology",
      "Public Health",
      "Social Work",
      "Sociology",
    ],
  },
  {
    label: "Humanities",
    options: [
      "English",
      "Ethnic Studies",
      "History",
      "Linguistics",
      "Philosophy",
      "World Languages",
    ],
  },
  {
    label: "Still deciding",
    options: ["Undeclared / exploring"],
  },
];
